FROM node:lts AS runtime
WORKDIR /app

COPY . .

ARG PUBLIC_TURNSTILE_SITE_KEY
ARG TURNSTILE_SECRET_KEY
ARG PUBLIC_UNSHORTENER_LINK
ARG REDIS_URL
ARG DATABASE_URL

ENV PUBLIC_TURNSTILE_SITE_KEY=${PUBLIC_TURNSTILE_SITE_KEY}
ENV TURNSTILE_SECRET_KEY=${TURNSTILE_SECRET_KEY}
ENV PUBLIC_UNSHORTENER_LINK=${PUBLIC_UNSHORTENER_LINK}
ENV REDIS_URL=${REDIS_URL}
ENV DATABASE_URL=${DATABASE_URL}

RUN npm install
RUN npm run build

ENV HOST=0.0.0.0
ENV PORT=4321
ENV NODE_ENV=production

EXPOSE 4321

CMD npm run start
